### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by Lewiscowles1986** [OhMyCatile/ExtractHar#1]
One of your "friends" I'm guessing linked the C gist you'd created. It has been forked by me, one of the python authors into a working C example. https://github.com/Lewiscowles1986/har-img-extract

While forking I noticed some things you may or not have noticed, that I wasn't sure if your parser implemented.

- [ ] Not all text is base64, there is an `encoding` on the response content. It being missing or not base64, is what I'm calling literal mode. File-formats such as SVG (without G-zip) may use this.

- [ ] I Also noticed that text does not seem to be optional in your implementation. For 3XX responses this may not be set

Thanks for making this, it's very interesting to see how things translate to other languages, and to revisit and document little hacks.

**Comment by OhMyCatile** [comment]
Hi. My gist is something like a joke, I was interested in implementing a python script in c. You might have noticed that it's not finished, because I suddenly realized that I'm not ready to fix every mistake in such a low-level language) Anyway, thanks for your comments, I really overlooked them
